### ISSUE TITLE
interface {} is nil, not string

### ISSUE THREAD

**Issue by mdingemanse** [kg4zow/rmweb#1]
Thanks for this tool! USB web interface is enabled on my tablet and I'm on version 3.14.1.9.

Running `rmweb list` I get:

```
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
main.read_files()
        /Users/jms1/git/kg4zow/rmweb/read_files.go:114 +0xc6a
main.do_list({0x1c08188, 0x0, 0x0})
        /Users/jms1/git/kg4zow/rmweb/do_list.go:21 +0x26
main.main()
        /Users/jms1/git/kg4zow/rmweb/main.go:205 +0x3ba
```

Is that a hardcoded user string?

**Comment by kg4zow** [comment]
The path in the filenames is where the source code was on my laptop when I compiled the program.

The `read_files.go:114` is the filename and line number in the source code, which is [this line](https://github.com/kg4zow/rmweb/blob/main/read_files.go#L114).

It *looks like* maybe when it downloaded the list of files in that directory, one of the files didn't have a `sizeInBytes` entry. What software version is running on your tablet? Maybe reMarkable changed something *after* the 3.10 version I'm using.

**Comment by kg4zow** [comment]
I upgraded one of my experimenting tablets to 3.14 a few days ago, to test an [issue with the `rmbackup` script](https://github.com/kg4zow/rm2-scripts/issues/5). I just tried `rmweb` with that tablet, and got the same error message you did.

I added a debug message which shows the full JSON outputs when retrieving the list of files from the tablet. It looks like reMarkable changed the format of the JSON returned by the directory list request between 3.10 and 3.14, so it no longer contains the file size and page count. The built-in web interface doesn't show this information, so I guess they figure there's no need to include it.

I've updated the program so it *checks* whether these items are present. If not, it won't try to read them (which is what was causing the error message you found). In addition, the output of `rmweb list` won't include values in those columns. I thought about  removing those two columns entirely (if the values weren't there) but I decided to leave them, to remind myself that this is a case where reMarkable *removed* functionality that other programs were relying on. Unofficial third-party programs to be sure, but it's still a step in the wrong direction IMHO.

Please try the new version and let me know what happens.

https://github.com/kg4zow/rmweb/releases/tag/v0.8

**Comment by mdingemanse** [comment]
I agree with you! Don't have my tablet to try right now but this seems a good fix — can be closed as far as I'm concerned
